routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*

Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/', 'HomeController@index')->name('welcome');

Route::post('/reservation', 'ReservationController@reserve')->name('reservation');
Route::post('/contact', 'ContactController@sendMessage')->name('contact');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');


/*

Route::get('admin/dashboard', function(){
    return view('admin.dashboard');
});

*/

Route::group(['prefix'=>'admin', 'middleware'=>'auth', 'namespace'=>'admin'], function(){
    Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
    Route::resource('slider', 'SliderController');
    Route::resource('category', 'CategoryController');
    Route::resource('item', 'ItemController');
    Route::get('reservation', 'ReservationController@index')->name('reservation.index');
    Route::post('reservation/{id}', 'ReservationController@status')->name('reservation.status');
    Route::delete('reservation/{id}', 'ReservationController@destroy')->name('reservation.destroy');

    Route::get('contact', 'ContactController@index')->name('contact.index');
    Route::get('contact/{id}', 'ContactController@show')->name('contact.show');
    Route::delete('contact/{id}', 'ContactController@destroy')->name('contact.destroy');
});

Route::get('/temp', 'HomeController@temp');

resources/views/layouts/include/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>
                <li>
                    <a href="#">
                        Home
                    </a>
                </li>

                <li>
                    <a href="#">
                        Company
                    </a>
                </li>

                <li>
                    <a href="#">
                        Portfolio
                    </a>
                </li>

                <li>
                    <a href="#">
                        Blog
                    </a>
                </li>
            </ul>
        </nav>

        <p class="copyright pull-right">
            &copy; Copyright, {{-- date('Y') --}}
            <script>
                document.write(new Date().getFullYear())
            </script>
            <a href="http://www.creative-tim.com">Creative Tim</a> and Developed by <a href="http://github.com/ashrafshovo" target="_blank">Ashraf Hossan Shovo</a>.
        </p>

    </div>
</footer>

resources/views/layouts/include/msg.blade.php
@if ($errors->any())
    @foreach ($errors->all() as $error)
        <div class="alert alert-danger">
            <button type="button" aria-hidden="true" class="close"
            onclick="this.parentElement.style.display='none'">×</button>
            <span><b> Danger - </b>{{ $error }}</span>
        </div>
    @endforeach
@endif

@if (session('successMsg'))
    <div class="alert alert-success">
        <button type="button" aria-hidden="true" class="close"
        onclick="this.parentElement.style.display='none'">×</button>
        <span><b> Success - </b>{{ session('successMsg') }}</span>
    </div>
@endif

resources/views/layouts/include/sidebar.blade.php
<div class="sidebar" data-color="purple" data-image="{{ asset('back/img/sidebar-1.jpg') }}">
            <!--
            Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

            Tip 2: you can also add an image using data-image tag
            -->
            <div class="logo">
                <a href="{{ route('admin.dashboard') }}" class="simple-text">
                    {{ Auth::user()->name }}
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="{{ Request::is('admin/dashboard*')? 'active': '' }}">
                        <a href="{{ route('admin.dashboard') }}">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/slider*')? 'active': '' }}">
                        <a href="{{ route('slider.index') }}">
                            <i class="material-icons">slideshow</i>
                            <p>Sliders</p>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/category*')? 'active': '' }}">
                        <a href="{{ route('category.index') }}">
                            <i class="material-icons">content_paste</i>
                            <p>Categories</p>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/item*')? 'active': '' }}">
                        <a href="{{ route('item.index') }}">
                            <i class="material-icons">library_books</i>
                            <p>Items</p>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/reservation*')? 'active': '' }}">
                        <a href="{{ route('reservation.index') }}">
                            <i class="material-icons">chrome_reader_mode</i>
                            <p>Reservations</p>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/contact*')? 'active': '' }}">
                        <a href="{{ route('contact.index') }}">
                            <i class="material-icons">message</i>
                            <p>Contact Message</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

resources/views/layouts/include/topbar.blade.php
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ route('admin.dashboard') }}"> Mama's Kitchen </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{{ route('admin.dashboard') }}">
                        <i class="material-icons">dashboard</i>
                        <p class="hidden-lg hidden-md">Dashboard</p>
                    </a>
                </li>
                <li>
                    <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">person</i>
                        <p class="hidden-lg hidden-md">Profile</p>
                    </a>
                </li>
                <li>
                    <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        <i class="material-icons">exit_to_app</i>
                        <p class="hidden-lg hidden-md">Logout</p>
                        <form id="logout-form" method="post" action="{{ route('logout') }}" style="display:none;">
                            @csrf
                        </form>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>